//! AES-256-GCM helpers for at-rest secret encryption.
//!
//! The master key is generated by `Bootstrapper::bootstrap_encryption_key`,
//! stored in the catalog at `key_material:enc`, and loaded into memory at
//! server startup via `BigtableCatalogStore::cached_encryption_key`.

use aes_gcm::aead::Aead;
use aes_gcm::{Aes256Gcm, Key, KeyInit, Nonce};
use base64::Engine;
use rand::{TryRngCore, rngs::OsRng};

/// Encrypt `plaintext` with the base64-encoded 32-byte master key. Returns
/// `base64(nonce || ciphertext)` where the nonce is 12 bytes of random data.
pub fn encrypt(master_key_b64: &str, plaintext: &[u8]) -> Result<String, String> {
    let key_bytes = base64::engine::general_purpose::STANDARD
        .decode(master_key_b64)
        .map_err(|e| format!("decode master key: {e}"))?;
    if key_bytes.len() != 32 {
        return Err(format!("master key must be 32 bytes, got {}", key_bytes.len()));
    }
    let key = Key::<Aes256Gcm>::from_slice(&key_bytes);
    let cipher = Aes256Gcm::new(key);

    let mut nonce_bytes = [0u8; 12];
    OsRng
        .try_fill_bytes(&mut nonce_bytes)
        .map_err(|e| format!("rng: {e}"))?;
    let nonce = Nonce::from_slice(&nonce_bytes);

    let ciphertext = cipher
        .encrypt(nonce, plaintext)
        .map_err(|e| format!("encrypt: {e}"))?;

    let mut combined = Vec::with_capacity(12 + ciphertext.len());
    combined.extend_from_slice(&nonce_bytes);
    combined.extend_from_slice(&ciphertext);
    Ok(base64::engine::general_purpose::STANDARD.encode(&combined))
}

/// Inverse of `encrypt`. Returns the plaintext bytes.
pub fn decrypt(master_key_b64: &str, sealed_b64: &str) -> Result<Vec<u8>, String> {
    let key_bytes = base64::engine::general_purpose::STANDARD
        .decode(master_key_b64)
        .map_err(|e| format!("decode master key: {e}"))?;
    if key_bytes.len() != 32 {
        return Err(format!("master key must be 32 bytes, got {}", key_bytes.len()));
    }
    let key = Key::<Aes256Gcm>::from_slice(&key_bytes);
    let cipher = Aes256Gcm::new(key);

    let combined = base64::engine::general_purpose::STANDARD
        .decode(sealed_b64)
        .map_err(|e| format!("decode sealed: {e}"))?;
    if combined.len() < 12 + 16 {
        return Err("sealed payload too short".into());
    }
    let (nonce_bytes, ciphertext) = combined.split_at(12);
    let nonce = Nonce::from_slice(nonce_bytes);

    cipher
        .decrypt(nonce, ciphertext)
        .map_err(|e| format!("decrypt: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roundtrip() {
        let mut key = [0u8; 32];
        OsRng.try_fill_bytes(&mut key).unwrap();
        let key_b64 = base64::engine::general_purpose::STANDARD.encode(key);
        let plaintext = b"super-secret-access-key-material";
        let sealed = encrypt(&key_b64, plaintext).unwrap();
        let decrypted = decrypt(&key_b64, &sealed).unwrap();
        assert_eq!(plaintext.as_slice(), decrypted.as_slice());
    }

    #[test]
    fn each_encrypt_uses_fresh_nonce() {
        // Same plaintext → different ciphertext each time (random nonce).
        let mut key = [0u8; 32];
        OsRng.try_fill_bytes(&mut key).unwrap();
        let key_b64 = base64::engine::general_purpose::STANDARD.encode(key);
        let a = encrypt(&key_b64, b"x").unwrap();
        let b = encrypt(&key_b64, b"x").unwrap();
        assert_ne!(a, b);
    }
}
